# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Attorg Test"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

#plugins:
#   Auth::Extensible:
#      

session: "YAML"
session_dir: "/home/bernt/wuala/attorg/session-storage"
# session: "Simple"

# For attorg specifics:
userdata_top: "/home/bernt/org_dir_top"

plugins:
   Auth::Extensible:
      realms:
          config:
              provider: Config
              users:
                  - user: bug
                    pass: fubar
                    roles:
                      - Developer
                      - Manager
                      - BeerDrinker
                  # - user: bob
                  #   pass: '{SSHA}+2u1HpOU7ak6iBR6JlpICpAUvSpA/zBM'
                  #   roles:
                  #     - Tester

template: "template_toolkit"
engines:
   template_toolkit:
     encoding:  'utf8'
     start_tag: '[%'
     end_tag:   '%]'

